// Code generated by mockery v2.43.2. DO NOT EDIT.

package storagemocks

import (
	context "context"

	cr "github.com/lorenzoMrt/ContentInsight/internal"
	mock "github.com/stretchr/testify/mock"
)

// ContentRepository is an autogenerated mock type for the ContentRepository type
type ContentRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, content
func (_m *ContentRepository) Save(ctx context.Context, content cr.Content) error {
	ret := _m.Called(ctx, content)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, cr.Content) error); ok {
		r0 = rf(ctx, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewContentRepository creates a new instance of ContentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContentRepository {
	mock := &ContentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
